name: Auto Update News

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python packages
        run: pip install feedparser

      - name: Run script
        run: python fetch.py

      - name: Commit updated JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add news.json
          git commit -m "Auto update news"
          git push
